apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: globex-web
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: globex-web
    app.kubernetes.io/part-of: globex-web
  name: globex-web
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: globex-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: globex-web
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rshah-tenant/globex-web/globex-web@sha256:cf0116555a2225f5b9ad5df583f3e14b6689acf7ee2bca9aaa29794b8b2e6b44
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
