apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: globex-web
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: globex-web
    app.kubernetes.io/part-of: globex-web
  name: globex-web
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: globex-web
status:
  loadBalancer: {}
